[[pages]]
path = "app/main.py"
name = "ğŸ  Inicio"
icon = "house"

[[pages]]
path = "app/pages/rain.py"
name = "â˜” Choiva"
icon = "cloud-rain"

[[pages]]
path = "app/pages/temperature.py"
name = "ğŸŒ¡ï¸ Temperatura"
icon = "thermometer"

[[pages]]
path = "app/pages/humidity.py"
name = "ğŸŒ«ï¸ Humidade"
icon = "ğŸŒ«ï¸"
